// Map exercise ID to bundled asset
// React Native requires static require() calls
const images: Record<number, any> = {
  1: require('../../assets/exercises/1.jpg'),
  2: require('../../assets/exercises/2.jpg'),
  3: require('../../assets/exercises/3.jpg'),
  4: require('../../assets/exercises/4.jpg'),
  5: require('../../assets/exercises/5.jpg'),
  6: require('../../assets/exercises/6.jpg'),
  7: require('../../assets/exercises/7.jpg'),
  9: require('../../assets/exercises/9.jpg'),
  10: require('../../assets/exercises/10.jpg'),
  11: require('../../assets/exercises/11.jpg'),
  12: require('../../assets/exercises/12.jpg'),
  13: require('../../assets/exercises/13.jpg'),
  14: require('../../assets/exercises/14.jpg'),
  15: require('../../assets/exercises/15.jpg'),
  16: require('../../assets/exercises/16.jpg'),
  17: require('../../assets/exercises/17.jpg'),
  18: require('../../assets/exercises/18.jpg'),
  20: require('../../assets/exercises/20.jpg'),
  21: require('../../assets/exercises/21.jpg'),
  22: require('../../assets/exercises/22.jpg'),
  23: require('../../assets/exercises/23.jpg'),
  24: require('../../assets/exercises/24.jpg'),
  25: require('../../assets/exercises/25.jpg'),
  26: require('../../assets/exercises/26.jpg'),
  27: require('../../assets/exercises/27.jpg'),
  30: require('../../assets/exercises/30.jpg'),
  31: require('../../assets/exercises/31.jpg'),
  32: require('../../assets/exercises/32.jpg'),
  33: require('../../assets/exercises/33.jpg'),
  35: require('../../assets/exercises/35.jpg'),
  36: require('../../assets/exercises/36.jpg'),
  37: require('../../assets/exercises/37.jpg'),
  38: require('../../assets/exercises/38.jpg'),
  39: require('../../assets/exercises/39.jpg'),
  40: require('../../assets/exercises/40.jpg'),
  41: require('../../assets/exercises/41.jpg'),
  42: require('../../assets/exercises/42.jpg'),
  43: require('../../assets/exercises/43.jpg'),
  44: require('../../assets/exercises/44.jpg'),
  45: require('../../assets/exercises/45.jpg'),
  48: require('../../assets/exercises/48.gif'),
  49: require('../../assets/exercises/49.gif'),
  50: require('../../assets/exercises/50.gif'),
  51: require('../../assets/exercises/51.gif'),
  52: require('../../assets/exercises/52.gif'),
};

export default images;
